import '../models/transaction_status.dart';
import '../models/user_model.dart';
import '../models/shipment_model.dart';
import '../models/journey_model.dart';
import '../models/transaction_model.dart';
import '../models/tracking_event_model.dart';
import '../models/courier_partner_model.dart';
import '../models/claim_model.dart';
import '../models/prohibited_rule_model.dart';
import '../models/audit_log_model.dart';
import '../models/notification_item.dart';

class MockDataService {
  static UserModel get currentUser => UserModel.demoSender;

  static List<JourneyModel> get initialJourneys => [
        JourneyModel(
          id: 'SMYL-JRN-2026',
          travellerId: 'trv_arjun_01',
          travellerName: 'Arjun Reddy',
          travellerRating: 4.8,
          travellerKycVerified: true,
          originCity: 'Hyderabad',
          originCountry: 'India',
          originAirportCode: 'HYD',
          destCity: 'Dubai',
          destCountry: 'United Arab Emirates',
          destAirportCode: 'DXB',
          departureDate: DateTime(2026, 10, 10),
          departureTime: '10:30 AM',
          arrivalDate: DateTime(2026, 10, 10),
          arrivalTime: '01:15 PM',
          airline: 'Emirates',
          flightNumber: 'EK-527',
          totalCapacityKg: 5.0,
          availableCapacityKg: 5.0,
          isInternational: true,
          handoverPreference: 'Airport Departure Gate 4',
          status: JourneyStatus.active,
          estimatedEarnings: 3750.0,
          acceptedShipmentIds: [],
        ),
        JourneyModel(
          id: 'SMYL-JRN-2092',
          travellerId: 'trv_priya_02',
          travellerName: 'Priya Sharma',
          travellerRating: 4.9,
          travellerKycVerified: true,
          originCity: 'Hyderabad',
          originCountry: 'India',
          originAirportCode: 'HYD',
          destCity: 'Dubai',
          destCountry: 'United Arab Emirates',
          destAirportCode: 'DXB',
          departureDate: DateTime(2026, 10, 10),
          departureTime: '06:45 PM',
          arrivalDate: DateTime(2026, 10, 10),
          arrivalTime: '09:30 PM',
          airline: 'Air India',
          flightNumber: 'AI-951',
          totalCapacityKg: 4.0,
          availableCapacityKg: 4.0,
          isInternational: true,
          handoverPreference: 'Terminal 1 Departure Lobby',
          status: JourneyStatus.active,
          estimatedEarnings: 2800.0,
          acceptedShipmentIds: [],
        ),
        JourneyModel(
          id: 'SMYL-JRN-3042',
          travellerId: 'trv_sarah_03',
          travellerName: 'Sarah Jenkins',
          travellerRating: 5.0,
          travellerKycVerified: true,
          originCity: 'London',
          originCountry: 'United Kingdom',
          originAirportCode: 'LHR',
          destCity: 'New York',
          destCountry: 'United States',
          destAirportCode: 'JFK',
          departureDate: DateTime(2026, 10, 12),
          departureTime: '02:15 PM',
          arrivalDate: DateTime(2026, 10, 12),
          arrivalTime: '05:30 PM',
          airline: 'British Airways',
          flightNumber: 'BA-177',
          totalCapacityKg: 10.0,
          availableCapacityKg: 7.5,
          isInternational: true,
          handoverPreference: 'Heathrow T5 Drop-off',
          status: JourneyStatus.active,
          estimatedEarnings: 18200.0,
          acceptedShipmentIds: [],
        ),
      ];

  static List<ShipmentModel> get initialShipments => [
        ShipmentModel(
          id: 'SMYL-2026-000184',
          senderId: 'usr_lakshmi_01',
          senderName: 'Lakshmi Narayana',
          pickupCity: 'Hyderabad',
          pickupCountry: 'India',
          pickupAddress: 'Banjara Hills, Road No. 12',
          destCity: 'Dubai',
          destCountry: 'United Arab Emirates',
          destAddress: 'Downtown Dubai, UAE',
          receiverName: 'Rahul Kumar',
          receiverPhone: '+971 50 123 4567',
          receiverInstructions: 'Handover at Downtown Dubai residence or building reception.',
          itemCategory: 'Personal permitted item',
          itemDescription: 'Hand-woven Pashmina & Traditional Indian Confectionery',
          weightKg: 2.0,
          quantity: 1,
          isFragile: true,
          declaredValue: 8000.0,
          currency: 'INR',
          journeyType: JourneyType.international,
          specialInstructions: 'Handle with care; keep in dry condition inside airline cabin.',
          declarationAccepted: true,
          estimatedCost: 2230.0,
          travellerPayout: 1800.0,
          platformFee: 180.0,
          courierFee: 250.0,
          matchedTravellerId: null,
          matchedTravellerName: null,
          status: TransactionStatus.openForMatching,
          originOtp: '482913',
          deliveryOtp: '739104',
          createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
        ),
      ];

  static List<TransactionModel> get initialTransactions => [
        TransactionModel(
          id: 'SMYL-2026-000184',
          shipmentId: 'SMYL-2026-000184',
          journeyId: 'SMYL-JRN-2026',
          senderId: 'usr_lakshmi_01',
          senderName: 'Lakshmi Narayana',
          travellerId: 'trv_arjun_01',
          travellerName: 'Arjun Reddy',
          receiverName: 'Rahul Kumar',
          receiverPhone: '+971 50 123 4567',
          originCity: 'Hyderabad',
          originCountry: 'India',
          originAirportCode: 'HYD',
          destCity: 'Dubai',
          destCountry: 'UAE',
          destAirportCode: 'DXB',
          itemCategory: 'Personal permitted item',
          itemDescription: 'Hand-woven Pashmina & Traditional Indian Confectionery',
          weightKg: 2.0,
          status: TransactionStatus.openForMatching,
          paymentStatus: PaymentStatus.pending,
          totalAmount: 2230.0,
          travellerPayout: 1800.0,
          platformFee: 180.0,
          courierFee: 250.0,
          originHandoverOtp: '482913',
          destinationHandoverOtp: '739104',
          courierPartnerId: 'cr_smyl_logistics',
          courierPartnerName: 'SMYL Logistics Partner',
          courierTrackingId: 'SML-CP-829104',
          paymentReference: 'SMYL-PAY-2026-008721',
          createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
          updatedAt: DateTime.now().subtract(const Duration(minutes: 45)),
        ),
      ];

  static List<TrackingEventModel> getTrackingEvents(String transactionId, [TransactionStatus? currentStatus]) {
    final now = DateTime.now();
    final status = currentStatus ?? TransactionStatus.openForMatching;
    final progress = status.standardProgressIndex;

    return [
      TrackingEventModel(
        id: 'evt_01',
        transactionId: transactionId,
        status: TransactionStatus.created,
        title: 'Shipment Created',
        description: 'Lakshmi Narayana created delivery order for 2.0 KG personal item.',
        location: 'Hyderabad, India',
        timestamp: now.subtract(const Duration(minutes: 45)),
        actor: 'Lakshmi Narayana (Sender)',
        eventType: 'SHIPMENT_CREATED',
        isCompleted: true,
      ),
      TrackingEventModel(
        id: 'evt_02',
        transactionId: transactionId,
        status: TransactionStatus.travellerRequested,
        title: 'Traveller Selected',
        description: 'Consignment request sent to verified traveller Arjun Reddy (EK-527).',
        location: 'SMYL Matching Engine',
        timestamp: now.subtract(const Duration(minutes: 38)),
        actor: 'Lakshmi Narayana (Sender)',
        eventType: 'TRAVELLER_REQUESTED',
        isCompleted: progress >= 1,
      ),
      TrackingEventModel(
        id: 'evt_03',
        transactionId: transactionId,
        status: TransactionStatus.accepted,
        title: 'Traveller Accepted',
        description: 'Arjun Reddy accepted to carry consignment on flight EK-527.',
        location: 'Verified Traveller Portal',
        timestamp: now.subtract(const Duration(minutes: 30)),
        actor: 'Arjun Reddy (Traveller)',
        eventType: 'REQUEST_ACCEPTED',
        isCompleted: progress >= 2,
      ),
      TrackingEventModel(
        id: 'evt_04',
        transactionId: transactionId,
        status: TransactionStatus.paymentConfirmed,
        title: 'Payment Confirmed in Escrow',
        description: '₹1,850.00 secured in SMYL Escrow (Ref: PAY-2026-008721).',
        location: 'SMYL Financial Gateway',
        timestamp: now.subtract(const Duration(minutes: 20)),
        actor: 'System Escrow',
        eventType: 'PAYMENT_CONFIRMED',
        isCompleted: progress >= 3,
      ),
      TrackingEventModel(
        id: 'evt_05',
        transactionId: transactionId,
        status: TransactionStatus.readyForHandover,
        title: 'Ready for Handover',
        description: 'Secure 6-digit origin OTP generated for physical inspection.',
        location: 'Rajiv Gandhi Int\'l Airport (HYD)',
        timestamp: now.subtract(const Duration(minutes: 15)),
        actor: 'System',
        eventType: 'READY_FOR_HANDOVER',
        isCompleted: progress >= 4,
      ),
      TrackingEventModel(
        id: 'evt_06',
        transactionId: transactionId,
        status: TransactionStatus.handedToTraveller,
        title: 'Handover Confirmed via OTP',
        description: 'Inspection complete and OTP 482913 verified at Departure Gate 4.',
        location: 'HYD Terminal 1 Departure',
        timestamp: now.subtract(const Duration(minutes: 10)),
        actor: 'Arjun Reddy (Traveller)',
        eventType: 'HANDOVER_VERIFIED',
        isCompleted: progress >= 5,
      ),
      TrackingEventModel(
        id: 'evt_07',
        transactionId: transactionId,
        status: TransactionStatus.inTransit,
        title: 'In Flight (HYD → DXB)',
        description: 'Flight EK-527 en route to Dubai International Airport.',
        location: 'Arabian Sea Airspace • 36,000 FT',
        timestamp: now.subtract(const Duration(minutes: 5)),
        actor: 'Arjun Reddy (Traveller)',
        eventType: 'JOURNEY_STARTED',
        isCompleted: progress >= 6,
      ),
      TrackingEventModel(
        id: 'evt_08',
        transactionId: transactionId,
        status: TransactionStatus.arrivedAtDestination,
        title: 'Arrived at Destination Airport',
        description: 'Flight EK-527 touched down at Dubai International Terminal 3.',
        location: 'Dubai International (DXB)',
        timestamp: now,
        actor: 'Arjun Reddy (Traveller)',
        eventType: 'ARRIVED_AT_DESTINATION',
        isCompleted: progress >= 7,
      ),
      TrackingEventModel(
        id: 'evt_09',
        transactionId: transactionId,
        status: TransactionStatus.withCourierPartner,
        title: 'Onward Courier Delivery',
        description: 'Package transferred to SMYL Logistics Partner (CP-882190).',
        location: 'DXB Cargo Hub, UAE',
        timestamp: now.add(const Duration(minutes: 30)),
        actor: 'Operations Admin',
        eventType: 'COURIER_ASSIGNED',
        isCompleted: progress >= 8,
      ),
      TrackingEventModel(
        id: 'evt_10',
        transactionId: transactionId,
        status: TransactionStatus.delivered,
        title: 'Delivered to Receiver',
        description: 'Rahul Kumar verified delivery OTP 739104. Escrow payout released.',
        location: 'Downtown Dubai, UAE',
        timestamp: now.add(const Duration(hours: 1)),
        actor: 'Rahul Kumar (Receiver)',
        eventType: 'DELIVERY_CONFIRMED',
        isCompleted: progress >= 9,
      ),
    ];
  }

  static List<CourierPartnerModel> get initialCourierPartners => const [
        CourierPartnerModel(
          id: 'cr_smyl_logistics',
          name: 'SMYL Logistics Partner',
          code: 'SLP',
          logoCode: 'slp',
          serviceTier: 'Priority Airport Transfer',
          contactSupport: '+971 4 800 7695',
          averageTransitHours: 3.5,
        ),
        CourierPartnerModel(
          id: 'cr_aramex_01',
          name: 'Aramex International',
          code: 'ARX',
          logoCode: 'arx',
          serviceTier: 'Priority Air Express',
          contactSupport: '+971 600 544000',
          averageTransitHours: 6.5,
        ),
        CourierPartnerModel(
          id: 'cr_dhl_02',
          name: 'DHL Global Express',
          code: 'DHL',
          logoCode: 'dhl',
          serviceTier: 'Same-Day Express',
          contactSupport: '+44 844 248 0844',
          averageTransitHours: 4.0,
        ),
      ];

  static List<ClaimModel> get initialClaims => [
        ClaimModel(
          id: 'CLAIM-2026-0014',
          transactionId: 'SMYL-2026-000184',
          userId: 'rcv_rahul_01',
          userName: 'Rahul Kumar',
          issueType: ClaimIssueType.damagedItem,
          description: 'Package outer carton was compressed during flight handling. Cosmetic packaging creased.',
          declaredItemValue: 8000.0,
          status: ClaimStatus.claimOpen,
          resolutionSummary: 'Claim received by operations. Underwriter review in progress. Escrow hold applied.',
          createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
        ),
      ];

  static List<ProhibitedRuleModel> get initialProhibitedRules => const [
        ProhibitedRuleModel(
          id: 'RULE-01',
          category: 'Lithium Batteries',
          itemName: 'Loose Lithium Batteries & High-Capacity Powerbanks',
          restrictionLevel: RestrictionLevel.strictlyProhibited,
          rationale: 'IATA Dangerous Goods Regulation 2.3.5.9 fire hazard prohibition in checked luggage.',
          penaltyNotice: 'Confiscation at airport security and immediate traveller suspension.',
        ),
        ProhibitedRuleModel(
          id: 'RULE-02',
          category: 'Aerosols & Flammables',
          itemName: 'Perfumes (>100ml) & Pressurized Aerosol Sprays',
          restrictionLevel: RestrictionLevel.strictlyProhibited,
          rationale: 'Combustible liquid restrictions for passenger aircraft cabins and cargo holds.',
          penaltyNotice: 'Customs impoundment and cancellation of carrying privileges.',
        ),
        ProhibitedRuleModel(
          id: 'RULE-03',
          category: 'Agriculture & Food',
          itemName: 'Live Plants, Soil Samples & Uncertified Seeds',
          restrictionLevel: RestrictionLevel.strictlyProhibited,
          rationale: 'Strict international biosecurity laws to prevent invasive pest infestation.',
          penaltyNotice: 'Federal quarantine violation fines up to \$10,000 USD at port of entry.',
        ),
        ProhibitedRuleModel(
          id: 'RULE-04',
          category: 'Medications',
          itemName: 'Prescription Pharmaceuticals',
          restrictionLevel: RestrictionLevel.permitRequired,
          rationale: 'Must be accompanied by registered physician prescription matching patient identity.',
          penaltyNotice: 'Subject to border seizure unless full clinical documentation is attached.',
        ),
        ProhibitedRuleModel(
          id: 'RULE-05',
          category: 'High Value Luxury',
          itemName: 'Precious Metals & Gold Bullion (>20g)',
          restrictionLevel: RestrictionLevel.declarationRequired,
          rationale: 'Central Bank currency export declaration thresholds apply.',
          penaltyNotice: 'Mandatory export clearance customs stamp required prior to departure.',
        ),
      ];

  static List<AuditLogModel> get initialAuditLogs => [
        AuditLogModel(
          id: 'LOG-8812',
          adminId: 'adm_security_01',
          adminName: 'Operations Lead (SMYL HQ)',
          action: 'KYC Verification Approved',
          previousStatus: 'PENDING',
          newStatus: 'VERIFIED',
          referenceId: 'usr_lakshmi_01',
          entityType: 'User KYC',
          reason: 'Passport bio-page MRZ checksum and Aadhaar verified successfully against database.',
          timestamp: DateTime.now().subtract(const Duration(days: 30)),
        ),
        AuditLogModel(
          id: 'LOG-8940',
          adminId: 'adm_compliance_02',
          adminName: 'Customs Officer (Compliance)',
          action: 'Shipment Order Created',
          previousStatus: 'DRAFT',
          newStatus: 'OPEN_FOR_MATCHING',
          referenceId: 'SMYL-2026-000184',
          entityType: 'Shipment Order',
          reason: 'Shipment order SMYL-2026-000184 created by Lakshmi Narayana for Hyderabad -> Dubai route.',
          timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
        ),
      ];

  static List<NotificationItem> get initialNotifications => [
        NotificationItem(
          id: 'notif_01',
          title: 'Shipment Active: SMYL-2026-000184',
          body: 'Your shipment is open for verified traveller matching on the HYD → DXB route.',
          category: NotificationCategory.transaction,
          relatedTransactionId: 'SMYL-2026-000184',
          timestamp: DateTime.now().subtract(const Duration(minutes: 44)),
          isRead: false,
        ),
        NotificationItem(
          id: 'notif_02',
          title: 'KYC Identity Verified',
          body: 'Your passport bio-data and government ID have been verified. You can now carry consignments.',
          category: NotificationCategory.verification,
          timestamp: DateTime.now().subtract(const Duration(days: 5)),
          isRead: true,
        ),
      ];
}
